---
# wordpress deployment
apiVersion: apps/v1
kind: Deployment
metadata:
 name: wordpress-deployment
spec:
 replicas: 1
 selector:
   matchLabels:
    app: wordpress
 template:
  metadata:
   labels:
    app: wordpress
  spec:
    containers:
     - name: wordpress
       image: wordpress
       env:
        - name: WORDPRESS_DB_HOST
          value: mysql.default:3306
        - name: WORDPRESS_DB_NAME
          valueFrom:
           secretKeyRef:
            name: mysql-database
            key: database
        - name: WORDPRESS_DB_USER
          valueFrom:
           secretKeyRef:
            name: mysql-user-pass
            key: username       
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
           secretKeyRef:
            name: mysql-user-pass
            key: password   
       ports:
        - containerPort: 80
          name: wordpress              
---
# service for wordpress
apiVersion: v1
kind: Service
metadata: 
 name: wordpress-service
spec:
 type: NodePort
 selector:
   app: wordpress
 ports:
  - port: 80
    targetPort: 80
    nodePort: 30009
...               